//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ei_Dimension.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все файлы.
        /// </summary>
        public static string All_Files {
            get {
                return ResourceManager.GetString("All Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenuation %.
        /// </summary>
        public static string Calibration_Attenuation {
            get {
                return ResourceManager.GetString("Calibration_Attenuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        public static string Calibration_Classification_targets {
            get {
                return ResourceManager.GetString("Calibration_Classification_targets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Calibration_Height {
            get {
                return ResourceManager.GetString("Calibration_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High DNR Coefficient.
        /// </summary>
        public static string Calibration_High_DNR_Coeff {
            get {
                return ResourceManager.GetString("Calibration_High_DNR_Coeff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High DNR Transition.
        /// </summary>
        public static string Calibration_High_DNR_Trans {
            get {
                return ResourceManager.GetString("Calibration_High_DNR_Trans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max SSC.
        /// </summary>
        public static string Calibration_Max_SSC {
            get {
                return ResourceManager.GetString("Calibration_Max_SSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min SSC.
        /// </summary>
        public static string Calibration_Min_SSC {
            get {
                return ResourceManager.GetString("Calibration_Min_SSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Channels_Background {
            get {
                return ResourceManager.GetString("Channels_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bias @ 30ᴼC.
        /// </summary>
        public static string Channels_Bias {
            get {
                return ResourceManager.GetString("Channels_Bias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Scatter.
        /// </summary>
        public static string Channels_Forward_Scatter {
            get {
                return ResourceManager.GetString("Channels_Forward_Scatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green A (SSC).
        /// </summary>
        public static string Channels_Green_A {
            get {
                return ResourceManager.GetString("Channels_Green_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green B (PE 2%).
        /// </summary>
        public static string Channels_Green_B {
            get {
                return ResourceManager.GetString("Channels_Green_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green C PE.
        /// </summary>
        public static string Channels_Green_C {
            get {
                return ResourceManager.GetString("Channels_Green_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi Sensitivity
        ///    Channel.
        /// </summary>
        public static string Channels_Hi_Sens_Chan {
            get {
                return ResourceManager.GetString("Channels_Hi_Sens_Chan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red A (CL3).
        /// </summary>
        public static string Channels_Red_A {
            get {
                return ResourceManager.GetString("Channels_Red_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red B (SSC).
        /// </summary>
        public static string Channels_Red_B {
            get {
                return ResourceManager.GetString("Channels_Red_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red C (CL1).
        /// </summary>
        public static string Channels_Red_C {
            get {
                return ResourceManager.GetString("Channels_Red_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red D (CL2).
        /// </summary>
        public static string Channels_Red_D {
            get {
                return ResourceManager.GetString("Channels_Red_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Save Bias
        ///To Current
        ///       Map.
        /// </summary>
        public static string Channels_Save_Bias_To_Map {
            get {
                return ResourceManager.GetString("Channels_Save_Bias_To_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green B.
        /// </summary>
        public static string Channels_Sens_B {
            get {
                return ResourceManager.GetString("Channels_Sens_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green C.
        /// </summary>
        public static string Channels_Sens_C {
            get {
                return ResourceManager.GetString("Channels_Sens_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Offset.
        /// </summary>
        public static string Channels_Set_Offset {
            get {
                return ResourceManager.GetString("Channels_Set_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiPM Temp
        ///Coefficient.
        /// </summary>
        public static string Channels_SiPM_Temp_Coefficient {
            get {
                return ResourceManager.GetString("Channels_SiPM_Temp_Coefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tcomp Bias.
        /// </summary>
        public static string Channels_Tcomp_Bias {
            get {
                return ResourceManager.GetString("Channels_Tcomp_Bias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update
        ///   Bias.
        /// </summary>
        public static string Channels_Update_Bias {
            get {
                return ResourceManager.GetString("Channels_Update_Bias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet A (SSC).
        /// </summary>
        public static string Channels_Violet_A {
            get {
                return ResourceManager.GetString("Channels_Violet_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet B (CL0).
        /// </summary>
        public static string Channels_Violet_B {
            get {
                return ResourceManager.GetString("Channels_Violet_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CL0.
        /// </summary>
        public static string CL0 {
            get {
                return ResourceManager.GetString("CL0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CL1.
        /// </summary>
        public static string CL1 {
            get {
                return ResourceManager.GetString("CL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CL2.
        /// </summary>
        public static string CL2 {
            get {
                return ResourceManager.GetString("CL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CL3.
        /// </summary>
        public static string CL3 {
            get {
                return ResourceManager.GetString("CL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuvet Drain.
        /// </summary>
        public static string Components_Cuvet_Drain_Open {
            get {
                return ResourceManager.GetString("Components_Cuvet_Drain_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      CW.
        /// </summary>
        public static string Components_CW_Dir {
            get {
                return ResourceManager.GetString("Components_CW_Dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вентилятор.
        /// </summary>
        public static string Components_Fan {
            get {
                return ResourceManager.GetString("Components_Fan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluidics.
        /// </summary>
        public static string Components_Fluidics {
            get {
                return ResourceManager.GetString("Components_Fluidics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Selector.
        /// </summary>
        public static string Components_Input_Sel {
            get {
                return ResourceManager.GetString("Components_Input_Sel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Idex.
        /// </summary>
        public static string Components_Move_Idex {
            get {
                return ResourceManager.GetString("Components_Move_Idex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime.
        /// </summary>
        public static string Components_Prime {
            get {
                return ResourceManager.GetString("Components_Prime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В кювет.
        /// </summary>
        public static string Components_To_Cuvet {
            get {
                return ResourceManager.GetString("Components_To_Cuvet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Pickup.
        /// </summary>
        public static string Components_To_Pickup {
            get {
                return ResourceManager.GetString("Components_To_Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve 1.
        /// </summary>
        public static string Components_Valve1 {
            get {
                return ResourceManager.GetString("Components_Valve1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve 2.
        /// </summary>
        public static string Components_Valve2 {
            get {
                return ResourceManager.GetString("Components_Valve2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valves.
        /// </summary>
        public static string Components_Valves {
            get {
                return ResourceManager.GetString("Components_Valves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wash A.
        /// </summary>
        public static string Components_Wash_A {
            get {
                return ResourceManager.GetString("Components_Wash_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wash B.
        /// </summary>
        public static string Components_Wash_B {
            get {
                return ResourceManager.GetString("Components_Wash_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        public static string Counter {
            get {
                return ResourceManager.GetString("Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Active.
        /// </summary>
        public static string Dashboard_Active_Region {
            get {
                return ResourceManager.GetString("Dashboard_Active_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Template:.
        /// </summary>
        public static string Dashboard_Current_Template {
            get {
                return ResourceManager.GetString("Dashboard_Current_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Inactive.
        /// </summary>
        public static string Dashboard_Inactive_Region {
            get {
                return ResourceManager.GetString("Dashboard_Inactive_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Dashboard_Name_Regions {
            get {
                return ResourceManager.GetString("Dashboard_Name_Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure Monitor.
        /// </summary>
        public static string Dashboard_Pressure_Mon {
            get {
                return ResourceManager.GetString("Dashboard_Pressure_Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Pressure.
        /// </summary>
        public static string Dashboard_Pressure_Mon_Max {
            get {
                return ResourceManager.GetString("Dashboard_Pressure_Mon_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Pressure.
        /// </summary>
        public static string Dashboard_Pressure_Mon_Min {
            get {
                return ResourceManager.GetString("Dashboard_Pressure_Mon_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sel.
        /// </summary>
        public static string Dashboard_Select_Regions {
            get {
                return ResourceManager.GetString("Dashboard_Select_Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration
        ///  Statistics.
        /// </summary>
        public static string DataAn_Calib_stats {
            get {
                return ResourceManager.GetString("DataAn_Calib_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV.
        /// </summary>
        public static string DataAn_CV {
            get {
                return ResourceManager.GetString("DataAn_CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSC.
        /// </summary>
        public static string DataAn_FSC {
            get {
                return ResourceManager.GetString("DataAn_FSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Maj.
        /// </summary>
        public static string DataAn_Green_Maj {
            get {
                return ResourceManager.GetString("DataAn_Green_Maj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Min.
        /// </summary>
        public static string DataAn_Green_Min {
            get {
                return ResourceManager.GetString("DataAn_Green_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green SSC.
        /// </summary>
        public static string DataAn_Green_SSC {
            get {
                return ResourceManager.GetString("DataAn_Green_SSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFI.
        /// </summary>
        public static string DataAn_MFI {
            get {
                return ResourceManager.GetString("DataAn_MFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red SSC.
        /// </summary>
        public static string DataAn_Red_SSC {
            get {
                return ResourceManager.GetString("DataAn_Red_SSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet SSC.
        /// </summary>
        public static string DataAn_Violet_SSC {
            get {
                return ResourceManager.GetString("DataAn_Violet_SSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        public static string Dropdown_Boot {
            get {
                return ResourceManager.GetString("Dropdown_Boot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cells.
        /// </summary>
        public static string Dropdown_Cells {
            get {
                return ResourceManager.GetString("Dropdown_Cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FM3D.
        /// </summary>
        public static string Dropdown_FM3D {
            get {
                return ResourceManager.GetString("Dropdown_FM3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green + Red + RP bg.
        /// </summary>
        public static string Dropdown_Green_Red_Rp_bg {
            get {
                return ResourceManager.GetString("Dropdown_Green_Red_Rp_bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green + Red SSC.
        /// </summary>
        public static string Dropdown_Green_Red_SSC {
            get {
                return ResourceManager.GetString("Dropdown_Green_Red_SSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green + RP bg.
        /// </summary>
        public static string Dropdown_Green_Rp_bg {
            get {
                return ResourceManager.GetString("Dropdown_Green_Rp_bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green SSC.
        /// </summary>
        public static string Dropdown_Green_SSC {
            get {
                return ResourceManager.GetString("Dropdown_Green_SSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halt.
        /// </summary>
        public static string Dropdown_Halt {
            get {
                return ResourceManager.GetString("Dropdown_Halt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi Sensitivity.
        /// </summary>
        public static string Dropdown_Hi_Sens {
            get {
                return ResourceManager.GetString("Dropdown_Hi_Sens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi Speed.
        /// </summary>
        public static string Dropdown_Hi_Speed {
            get {
                return ResourceManager.GetString("Dropdown_Hi_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize.
        /// </summary>
        public static string Dropdown_Initialize {
            get {
                return ResourceManager.GetString("Dropdown_Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micro Step.
        /// </summary>
        public static string Dropdown_Micro_step {
            get {
                return ResourceManager.GetString("Dropdown_Micro_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Absolute.
        /// </summary>
        public static string Dropdown_Move_Absolute {
            get {
                return ResourceManager.GetString("Dropdown_Move_Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Dropdown_None {
            get {
                return ResourceManager.GetString("Dropdown_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Dropdown_Normal {
            get {
                return ResourceManager.GetString("Dropdown_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup.
        /// </summary>
        public static string Dropdown_Pickup {
            get {
                return ResourceManager.GetString("Dropdown_Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Dropdown_Pos {
            get {
                return ResourceManager.GetString("Dropdown_Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Inject.
        /// </summary>
        public static string Dropdown_Pre_inject {
            get {
                return ResourceManager.GetString("Dropdown_Pre_inject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТЕст.
        /// </summary>
        public static string Dropdown_Red_Rp_bg {
            get {
                return ResourceManager.GetString("Dropdown_Red_Rp_bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red SSC.
        /// </summary>
        public static string Dropdown_Red_SSC {
            get {
                return ResourceManager.GetString("Dropdown_Red_SSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RP bg.
        /// </summary>
        public static string Dropdown_Rp_bg {
            get {
                return ResourceManager.GetString("Dropdown_Rp_bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Dropdown_Speed {
            get {
                return ResourceManager.GetString("Dropdown_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Preset.
        /// </summary>
        public static string Dropdown_Speed_Preset {
            get {
                return ResourceManager.GetString("Dropdown_Speed_Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Dropdown_Standard {
            get {
                return ResourceManager.GetString("Dropdown_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve Left.
        /// </summary>
        public static string Dropdown_Valve_Left {
            get {
                return ResourceManager.GetString("Dropdown_Valve_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve Right.
        /// </summary>
        public static string Dropdown_Valve_Right {
            get {
                return ResourceManager.GetString("Dropdown_Valve_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Regions.
        /// </summary>
        public static string Experiment_Active_Regions {
            get {
                return ResourceManager.GetString("Experiment_Active_Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agitate Vol.
        /// </summary>
        public static string Experiment_Agitate_Vol {
            get {
                return ResourceManager.GetString("Experiment_Agitate_Vol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Regions.
        /// </summary>
        public static string Experiment_Available_Regions {
            get {
                return ResourceManager.GetString("Experiment_Available_Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Configuration.
        /// </summary>
        public static string Experiment_Ch_Config {
            get {
                return ResourceManager.GetString("Experiment_Ch_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification Map.
        /// </summary>
        public static string Experiment_Classific_Map {
            get {
                return ResourceManager.GetString("Experiment_Classific_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приборная
        ///Панель.
        /// </summary>
        public static string Experiment_Dashboard {
            get {
                return ResourceManager.GetString("Experiment_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Delete
        ///Template.
        /// </summary>
        public static string Experiment_Delete_Template {
            get {
                return ResourceManager.GetString("Experiment_Delete_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eject Plate.
        /// </summary>
        public static string Experiment_Eject {
            get {
                return ResourceManager.GetString("Experiment_Eject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string Experiment_End {
            get {
                return ResourceManager.GetString("Experiment_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of
        ///Sample.
        /// </summary>
        public static string Experiment_End_of_Sample {
            get {
                return ResourceManager.GetString("Experiment_End_of_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Read.
        /// </summary>
        public static string Experiment_End_Read {
            get {
                return ResourceManager.GetString("Experiment_End_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Count.
        /// </summary>
        public static string Experiment_Event_Count {
            get {
                return ResourceManager.GetString("Experiment_Event_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Files
        ///and Folder.
        /// </summary>
        public static string Experiment_FileSave {
            get {
                return ResourceManager.GetString("Experiment_FileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Plate.
        /// </summary>
        public static string Experiment_Load {
            get {
                return ResourceManager.GetString("Experiment_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load / Save
        ///Template.
        /// </summary>
        public static string Experiment_Load_Save_Template {
            get {
                return ResourceManager.GetString("Experiment_Load_Save_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load / Save Template.
        /// </summary>
        public static string Experiment_Load_Save_Template_1 {
            get {
                return ResourceManager.GetString("Experiment_Load_Save_Template_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть
        ///Шаблон.
        /// </summary>
        public static string Experiment_Load_Template {
            get {
                return ResourceManager.GetString("Experiment_Load_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть Шаблон.
        /// </summary>
        public static string Experiment_Load_Template_Dialog_Title {
            get {
                return ResourceManager.GetString("Experiment_Load_Template_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Experiment_Manual {
            get {
                return ResourceManager.GetString("Experiment_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Per
        ///Region.
        /// </summary>
        public static string Experiment_Min_Per_Reg {
            get {
                return ResourceManager.GetString("Experiment_Min_Per_Reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Experiment_Order {
            get {
                return ResourceManager.GetString("Experiment_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samp Vol.
        /// </summary>
        public static string Experiment_Samp_Vol {
            get {
                return ResourceManager.GetString("Experiment_Samp_Vol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить
        /// Шаблон.
        /// </summary>
        public static string Experiment_Save_Template {
            get {
                return ResourceManager.GetString("Experiment_Save_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить Шаблон.
        /// </summary>
        public static string Experiment_Save_Template_Dialog_Title {
            get {
                return ResourceManager.GetString("Experiment_Save_Template_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Active
        /// Regions.
        /// </summary>
        public static string Experiment_Sel_Active_Region {
            get {
                return ResourceManager.GetString("Experiment_Sel_Active_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Wells.
        /// </summary>
        public static string Experiment_Select_Wells {
            get {
                return ResourceManager.GetString("Experiment_Select_Wells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Experiment_Speed {
            get {
                return ResourceManager.GetString("Experiment_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Experiment_Start {
            get {
                return ResourceManager.GetString("Experiment_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Experiment_Stats {
            get {
                return ResourceManager.GetString("Experiment_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Control.
        /// </summary>
        public static string Experiment_System_Control {
            get {
                return ResourceManager.GetString("Experiment_System_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Monitor.
        /// </summary>
        public static string Experiment_System_Monitor {
            get {
                return ResourceManager.GetString("Experiment_System_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total
        ///Events.
        /// </summary>
        public static string Experiment_Total_Events {
            get {
                return ResourceManager.GetString("Experiment_Total_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tube.
        /// </summary>
        public static string Experiment_Tube {
            get {
                return ResourceManager.GetString("Experiment_Tube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate
        ///Barcode.
        /// </summary>
        public static string Experiment_Validate_Bcode {
            get {
                return ResourceManager.GetString("Experiment_Validate_Bcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wash Vol.
        /// </summary>
        public static string Experiment_Wash_Vol {
            get {
                return ResourceManager.GetString("Experiment_Wash_Vol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order.
        /// </summary>
        public static string Experiment_Work_Order {
            get {
                return ResourceManager.GetString("Experiment_Work_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order +
        ///  Barcode.
        /// </summary>
        public static string Experiment_Work_Order_Plus_Bcode {
            get {
                return ResourceManager.GetString("Experiment_Work_Order_Plus_Bcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base File Name.
        /// </summary>
        public static string FileSave_Base_Filename {
            get {
                return ResourceManager.GetString("FileSave_Base_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Unclassified Beads From Bead Event File.
        /// </summary>
        public static string FileSave_Discard_Unclassified_Beads {
            get {
                return ResourceManager.GetString("FileSave_Discard_Unclassified_Beads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string FileSave_Filters {
            get {
                return ResourceManager.GetString("FileSave_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Doublet Events in Bead Event File.
        /// </summary>
        public static string FileSave_Include_Doublet_Events {
            get {
                return ResourceManager.GetString("FileSave_Include_Doublet_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Unclassified Beads in Plate Summary File.
        /// </summary>
        public static string FileSave_Include_Unclassified_Beads {
            get {
                return ResourceManager.GetString("FileSave_Include_Unclassified_Beads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual Bead Events.
        /// </summary>
        public static string FileSave_Ind_Bead_Events {
            get {
                return ResourceManager.GetString("FileSave_Ind_Bead_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Resuts File.
        /// </summary>
        public static string FileSave_JSON_To_Results {
            get {
                return ResourceManager.GetString("FileSave_JSON_To_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Files.
        /// </summary>
        public static string FileSave_Output_Files {
            get {
                return ResourceManager.GetString("FileSave_Output_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Summary of MFI for All Regions.
        /// </summary>
        public static string FileSave_Plate_Summary {
            get {
                return ResourceManager.GetString("FileSave_Plate_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log to File.
        /// </summary>
        public static string FileSave_Sys_Log {
            get {
                return ResourceManager.GetString("FileSave_Sys_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halt.
        /// </summary>
        public static string Halt {
            get {
                return ResourceManager.GetString("Halt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Files.
        /// </summary>
        public static string JSON_Files {
            get {
                return ResourceManager.GetString("JSON_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Калибровка.
        /// </summary>
        public static string Maintenance_Calibration {
            get {
                return ResourceManager.GetString("Maintenance_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каналы.
        /// </summary>
        public static string Maintenance_Channels {
            get {
                return ResourceManager.GetString("Maintenance_Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LED
        ///Вкл.
        /// </summary>
        public static string Maintenance_LEDs {
            get {
                return ResourceManager.GetString("Maintenance_LEDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UVC Sanitize.
        /// </summary>
        public static string Maintenance_Sanitize {
            get {
                return ResourceManager.GetString("Maintenance_Sanitize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Mean.
        /// </summary>
        public static string Mean {
            get {
                return ResourceManager.GetString("Mean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 384W C1.
        /// </summary>
        public static string Motors_384W_C1 {
            get {
                return ResourceManager.GetString("Motors_384W_C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 384W C24.
        /// </summary>
        public static string Motors_384W_C24 {
            get {
                return ResourceManager.GetString("Motors_384W_C24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96W C1.
        /// </summary>
        public static string Motors_96W_C1 {
            get {
                return ResourceManager.GetString("Motors_96W_C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96W C12.
        /// </summary>
        public static string Motors_96W_C12 {
            get {
                return ResourceManager.GetString("Motors_96W_C12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1.
        /// </summary>
        public static string Motors_A1 {
            get {
                return ResourceManager.GetString("Motors_A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A12.
        /// </summary>
        public static string Motors_A12 {
            get {
                return ResourceManager.GetString("Motors_A12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Motors_Back {
            get {
                return ResourceManager.GetString("Motors_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Limit.
        /// </summary>
        public static string Motors_Cur_Limit {
            get {
                return ResourceManager.GetString("Motors_Cur_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Step.
        /// </summary>
        public static string Motors_Cur_Step {
            get {
                return ResourceManager.GetString("Motors_Cur_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string Motors_Down {
            get {
                return ResourceManager.GetString("Motors_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder Steps.
        /// </summary>
        public static string Motors_Enc_Steps {
            get {
                return ResourceManager.GetString("Motors_Enc_Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        public static string Motors_Front {
            get {
                return ResourceManager.GetString("Motors_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Well.
        /// </summary>
        public static string Motors_GoTo_Well {
            get {
                return ResourceManager.GetString("Motors_GoTo_Well", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1.
        /// </summary>
        public static string Motors_H1 {
            get {
                return ResourceManager.GetString("Motors_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H12.
        /// </summary>
        public static string Motors_H12 {
            get {
                return ResourceManager.GetString("Motors_H12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Motors_Left {
            get {
                return ResourceManager.GetString("Motors_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Well Selection.
        /// </summary>
        public static string Motors_Man_Well_Sel {
            get {
                return ResourceManager.GetString("Motors_Man_Well_Sel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll Step.
        /// </summary>
        public static string Motors_Poll_Step {
            get {
                return ResourceManager.GetString("Motors_Poll_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Motors_Right {
            get {
                return ResourceManager.GetString("Motors_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row A.
        /// </summary>
        public static string Motors_Row_A {
            get {
                return ResourceManager.GetString("Motors_Row_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row H.
        /// </summary>
        public static string Motors_Row_H {
            get {
                return ResourceManager.GetString("Motors_Row_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row P.
        /// </summary>
        public static string Motors_Row_P {
            get {
                return ResourceManager.GetString("Motors_Row_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run speed.
        /// </summary>
        public static string Motors_Run_Speed {
            get {
                return ResourceManager.GetString("Motors_Run_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slope.
        /// </summary>
        public static string Motors_Slope {
            get {
                return ResourceManager.GetString("Motors_Slope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Speed.
        /// </summary>
        public static string Motors_Start_Speed {
            get {
                return ResourceManager.GetString("Motors_Start_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        public static string Motors_Steps {
            get {
                return ResourceManager.GetString("Motors_Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string Motors_Up {
            get {
                return ResourceManager.GetString("Motors_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выкл.
        /// </summary>
        public static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вкл.
        /// </summary>
        public static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ei Dimension.
        /// </summary>
        public static string Program_Name {
            get {
                return ResourceManager.GetString("Program_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Измерение.
        /// </summary>
        public static string Ribbon_Acquire {
            get {
                return ResourceManager.GetString("Ribbon_Acquire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализ
        ///Данных.
        /// </summary>
        public static string Ribbon_Analysis {
            get {
                return ResourceManager.GetString("Ribbon_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string Ribbon_Maintenance {
            get {
                return ResourceManager.GetString("Ribbon_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты.
        /// </summary>
        public static string Ribbon_Results {
            get {
                return ResourceManager.GetString("Ribbon_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обслуживание.
        /// </summary>
        public static string Ribbon_Service {
            get {
                return ResourceManager.GetString("Ribbon_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RP1.
        /// </summary>
        public static string RP1 {
            get {
                return ResourceManager.GetString("RP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сек.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string Service_Alignment {
            get {
                return ResourceManager.GetString("Service_Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string Service_Ch_Offset {
            get {
                return ResourceManager.GetString("Service_Ch_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        public static string Service_Components {
            get {
                return ResourceManager.GetString("Service_Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Memory
        ///    Control.
        /// </summary>
        public static string Service_Memory_Control {
            get {
                return ResourceManager.GetString("Service_Memory_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Service_Memory_Restore {
            get {
                return ResourceManager.GetString("Service_Memory_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore
        ///Factory Defaults.
        /// </summary>
        public static string Service_Memory_Restore_Defaults {
            get {
                return ResourceManager.GetString("Service_Memory_Restore_Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string Service_Memory_Save_All {
            get {
                return ResourceManager.GetString("Service_Memory_Save_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motors.
        /// </summary>
        public static string Service_Motors {
            get {
                return ResourceManager.GetString("Service_Motors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syringe.
        /// </summary>
        public static string Service_Syringe_Speeds {
            get {
                return ResourceManager.GetString("Service_Syringe_Speeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speeds.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        public static string Temp {
            get {
                return ResourceManager.GetString("Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текстовые документы.
        /// </summary>
        public static string Text_Files {
            get {
                return ResourceManager.GetString("Text_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tube.
        /// </summary>
        public static string Tube {
            get {
                return ResourceManager.GetString("Tube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Plate.
        /// </summary>
        public static string WellSel_Reset_Plate {
            get {
                return ResourceManager.GetString("WellSel_Reset_Plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string WellSel_Select_ALL {
            get {
                return ResourceManager.GetString("WellSel_Select_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        public static string Z {
            get {
                return ResourceManager.GetString("Z", resourceCulture);
            }
        }
    }
}
