//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ei_Dimension.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Channels_Background {
            get {
                return ResourceManager.GetString("Channels_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bias @ 30ᴼC.
        /// </summary>
        public static string Channels_Bias {
            get {
                return ResourceManager.GetString("Channels_Bias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Scatter.
        /// </summary>
        public static string Channels_Forward_Scatter {
            get {
                return ResourceManager.GetString("Channels_Forward_Scatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green A (SSC).
        /// </summary>
        public static string Channels_Green_A {
            get {
                return ResourceManager.GetString("Channels_Green_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green B (PE 2%).
        /// </summary>
        public static string Channels_Green_B {
            get {
                return ResourceManager.GetString("Channels_Green_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green C PE.
        /// </summary>
        public static string Channels_Green_C {
            get {
                return ResourceManager.GetString("Channels_Green_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red A (CL3).
        /// </summary>
        public static string Channels_Red_A {
            get {
                return ResourceManager.GetString("Channels_Red_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red B (SSC).
        /// </summary>
        public static string Channels_Red_B {
            get {
                return ResourceManager.GetString("Channels_Red_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red C (CL1).
        /// </summary>
        public static string Channels_Red_C {
            get {
                return ResourceManager.GetString("Channels_Red_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red D (CL2).
        /// </summary>
        public static string Channels_Red_D {
            get {
                return ResourceManager.GetString("Channels_Red_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Save Bias
        ///To Current
        ///       Map.
        /// </summary>
        public static string Channels_Save_Bias_To_Map {
            get {
                return ResourceManager.GetString("Channels_Save_Bias_To_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiPM Temp
        ///Coefficient.
        /// </summary>
        public static string Channels_SiPM_Temp_Coefficient {
            get {
                return ResourceManager.GetString("Channels_SiPM_Temp_Coefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tcomp Bias.
        /// </summary>
        public static string Channels_Tcomp_Bias {
            get {
                return ResourceManager.GetString("Channels_Tcomp_Bias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update
        ///   Bias.
        /// </summary>
        public static string Channels_Update_Bias {
            get {
                return ResourceManager.GetString("Channels_Update_Bias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet A (SSC).
        /// </summary>
        public static string Channels_Violet_A {
            get {
                return ResourceManager.GetString("Channels_Violet_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet B (CL0).
        /// </summary>
        public static string Channels_Violet_B {
            get {
                return ResourceManager.GetString("Channels_Violet_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Калибровка.
        /// </summary>
        public static string Maintenance_Calibration {
            get {
                return ResourceManager.GetString("Maintenance_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каналы.
        /// </summary>
        public static string Maintenance_Channels {
            get {
                return ResourceManager.GetString("Maintenance_Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LED
        ///Вкл.
        /// </summary>
        public static string Maintenance_LEDs {
            get {
                return ResourceManager.GetString("Maintenance_LEDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UVC Sanitize.
        /// </summary>
        public static string Maintenance_Sanitize {
            get {
                return ResourceManager.GetString("Maintenance_Sanitize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ei Dimension.
        /// </summary>
        public static string Program_Name {
            get {
                return ResourceManager.GetString("Program_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Измерение.
        /// </summary>
        public static string Ribbon_Acquire {
            get {
                return ResourceManager.GetString("Ribbon_Acquire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализ
        ///Данных.
        /// </summary>
        public static string Ribbon_Analysis {
            get {
                return ResourceManager.GetString("Ribbon_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приборная
        ///Панель.
        /// </summary>
        public static string Ribbon_Dashboard {
            get {
                return ResourceManager.GetString("Ribbon_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string Ribbon_Maintenance {
            get {
                return ResourceManager.GetString("Ribbon_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты.
        /// </summary>
        public static string Ribbon_Results {
            get {
                return ResourceManager.GetString("Ribbon_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обслуживание.
        /// </summary>
        public static string Ribbon_Service {
            get {
                return ResourceManager.GetString("Ribbon_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сек.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        public static string Temp {
            get {
                return ResourceManager.GetString("Temp", resourceCulture);
            }
        }
    }
}
